name: FlatWorldGenerator
version: ${project.version}
load: startup
main: net.cheatcodemedia.flatworldgenerator.FlatWorldGenerator
authors: [Phil]
description: A fully configurable flat world generator
website: cheatcodemedia.net
